# coding: utf-8

"""
    Payments V1

    To facilitate the capability for consumers to make a payment or refund to service providers.

    The version of the OpenAPI document: v1.0
    Contact: developer-support@mtn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_transaction_status_response import PaymentTransactionStatusResponse

class TestPaymentTransactionStatusResponse(unittest.TestCase):
    """PaymentTransactionStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentTransactionStatusResponse:
        """Test PaymentTransactionStatusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentTransactionStatusResponse`
        """
        model = PaymentTransactionStatusResponse()
        if include_optional:
            return PaymentTransactionStatusResponse(
                status_code = '0000',
                status_message = '',
                correlator_id = '',
                customer_id = '231167543AR2',
                sequence_no = '12345',
                provider_transaction_id = 'FT172145YB21',
                data = openapi_client.models.payment_transaction_status_data.PaymentTransactionStatusData(
                    financial_transaction_id = '', 
                    status = 'Approved', 
                    request_type = '', 
                    fulfillment_status = '', 
                    transaction_ref_parent = '', 
                    transaction_description = '', 
                    amount = 3453.45, 
                    date = '2021-11-21T15:39:33.8838432+01:00', 
                    channel = 'USSD', 
                    product = '122309940', 
                    description = '', 
                    customer = openapi_client.models.customer_object.CustomerObject(
                        firstname = 'John', 
                        surname = 'Doe', 
                        email = 'johndoe@email.com', 
                        msisdn = '263897646890', ), 
                    charges = openapi_client.models.charges_object.ChargesObject(
                        amount = 90.99, 
                        payer = 'M', ), ),
                additional_information = openapi_client.models.additional_info_object.AdditionalInfoObject(
                    name = 'Product A', 
                    description = 'Prod_2349', ),
                details = openapi_client.models.details_object.DetailsObject(
                    brand = 'AB233', 
                    fulfillment_msisdn = '263897646890', 
                    issuer = 'VISA', ),
                links = openapi_client.models.payment_transaction_status_response__links.PaymentTransactionStatusResponse__Links(
                    self = openapi_client.models.payment_transaction_status_response__links_self.PaymentTransactionStatusResponse__Links_Self(
                        href = 'https://host:port/payments/v1/12345', ), )
            )
        else:
            return PaymentTransactionStatusResponse(
        )
        """

    def testPaymentTransactionStatusResponse(self):
        """Test PaymentTransactionStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
