# coding: utf-8

"""
    Payments V1

    To facilitate the capability for consumers to make a payment or refund to service providers.

    The version of the OpenAPI document: v1.0
    Contact: developer-support@mtn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.generate_a_payment_agreement_api import GenerateAPaymentAgreementApi


class TestGenerateAPaymentAgreementApi(unittest.TestCase):
    """GenerateAPaymentAgreementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GenerateAPaymentAgreementApi()

    def tearDown(self) -> None:
        pass

    def test_generate_payment_agreement(self) -> None:
        """Test case for generate_payment_agreement

        Provides the ability for a consumer to generate a payment agreement (Promise to Pay)
        """
        pass

    def test_get_payment_agreement_eligibility(self) -> None:
        """Test case for get_payment_agreement_eligibility

        Provides the ability for a consumer to check the eligibility status for payment agreement
        """
        pass


if __name__ == '__main__':
    unittest.main()
