# coding: utf-8

"""
    Payments V1

    To facilitate the capability for consumers to make a payment or refund to service providers.

    The version of the OpenAPI document: v1.0
    Contact: developer-support@mtn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.submit_payment_or_refund_request_api import SubmitPaymentOrRefundRequestApi


class TestSubmitPaymentOrRefundRequestApi(unittest.TestCase):
    """SubmitPaymentOrRefundRequestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubmitPaymentOrRefundRequestApi()

    def tearDown(self) -> None:
        pass

    def test_create_payment(self) -> None:
        """Test case for create_payment

        Provides the ability for a consumer to make a payment or refund to service providers.
        """
        pass


if __name__ == '__main__':
    unittest.main()
