# coding: utf-8

"""
    Payments V1

    To facilitate the capability for consumers to make a payment or refund to service providers.

    The version of the OpenAPI document: v1.0
    Contact: developer-support@mtn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.p2p_transfer_fee_check_api import P2pTransferFeeCheckApi


class TestP2pTransferFeeCheckApi(unittest.TestCase):
    """P2pTransferFeeCheckApi unit test stubs"""

    def setUp(self) -> None:
        self.api = P2pTransferFeeCheckApi()

    def tearDown(self) -> None:
        pass

    def test_inbound(self) -> None:
        """Test case for inbound

        check transfer fee/charges beforhand
        """
        pass


if __name__ == '__main__':
    unittest.main()
