# coding: utf-8

"""
    Payments V1

    To facilitate the capability for consumers to make a payment or refund to service providers.

    The version of the OpenAPI document: v1.0
    Contact: developer-support@mtn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.bank_account_debit import BankAccountDebit

class TestBankAccountDebit(unittest.TestCase):
    """BankAccountDebit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BankAccountDebit:
        """Test BankAccountDebit
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BankAccountDebit`
        """
        model = BankAccountDebit()
        if include_optional:
            return BankAccountDebit(
                account_number = '',
                account_number_type = '',
                bic = '',
                owner = '',
                bank = ''
            )
        else:
            return BankAccountDebit(
        )
        """

    def testBankAccountDebit(self):
        """Test BankAccountDebit"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
