# coding: utf-8

"""
    Payments V1

    To facilitate the capability for consumers to make a payment or refund to service providers.

    The version of the OpenAPI document: v1.0
    Contact: developer-support@mtn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.invoice_method import InvoiceMethod

class TestInvoiceMethod(unittest.TestCase):
    """InvoiceMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoiceMethod:
        """Test InvoiceMethod
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoiceMethod`
        """
        model = InvoiceMethod()
        if include_optional:
            return InvoiceMethod(
                id = '86rer4478878t991',
                type = 'trigger',
                frequency = 'on_call',
                start_date = '2021-03-20',
                end_date = '2021-09-20',
                retry_on_fail = True,
                deactivate_on_fail = 'true',
                callback_url = 'https://merchant-application-url/webhook-endpoint',
                retry_run = '1-5',
                retry_frequency = 'once'
            )
        else:
            return InvoiceMethod(
        )
        """

    def testInvoiceMethod(self):
        """Test InvoiceMethod"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
