# coding: utf-8

"""
    Payments V1

    To facilitate the capability for consumers to make a payment or refund to service providers.

    The version of the OpenAPI document: v1.0
    Contact: developer-support@mtn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_transaction_status_data import PaymentTransactionStatusData

class TestPaymentTransactionStatusData(unittest.TestCase):
    """PaymentTransactionStatusData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentTransactionStatusData:
        """Test PaymentTransactionStatusData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentTransactionStatusData`
        """
        model = PaymentTransactionStatusData()
        if include_optional:
            return PaymentTransactionStatusData(
                financial_transaction_id = '',
                status = 'Approved',
                request_type = '',
                fulfillment_status = '',
                transaction_ref_parent = '',
                transaction_description = '',
                amount = 3453.45,
                var_date = '2021-11-21T15:39:33.8838432+01:00',
                channel = 'USSD',
                product = '122309940',
                description = '',
                customer = openapi_client.models.customer_object.CustomerObject(
                    firstname = 'John', 
                    surname = 'Doe', 
                    email = 'johndoe@email.com', 
                    msisdn = '263897646890', ),
                charges = openapi_client.models.charges_object.ChargesObject(
                    amount = 90.99, 
                    payer = 'M', )
            )
        else:
            return PaymentTransactionStatusData(
        )
        """

    def testPaymentTransactionStatusData(self):
        """Test PaymentTransactionStatusData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
