# coding: utf-8

"""
    Payments V1

    To facilitate the capability for consumers to make a payment or refund to service providers.

    The version of the OpenAPI document: v1.0
    Contact: developer-support@mtn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.retrieve_payment_status_api import RetrievePaymentStatusApi


class TestRetrievePaymentStatusApi(unittest.TestCase):
    """RetrievePaymentStatusApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RetrievePaymentStatusApi()

    def tearDown(self) -> None:
        pass

    def test_get_payment_transaction_status(self) -> None:
        """Test case for get_payment_transaction_status

        Provides the status of a Payment Transaction to service providers.
        """
        pass


if __name__ == '__main__':
    unittest.main()
