# Generated by Django 5.0.1 on 2024-01-11 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email_address', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=150)),
                ('employer', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('grade_level', models.CharField(max_length=150)),
                ('enrollment_number', models.CharField(max_length=150, unique=True)),
                ('tuition', models.FloatField()),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='api.parent')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=55)),
                ('transaction_id', models.CharField(max_length=20)),
                ('payment_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
                ('enrollment_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='api.student')),
            ],
        ),
    ]
