# Generated by Django 5.0.1 on 2024-02-12 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_myuser_date_joined_remove_myuser_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('payer_account', models.CharField(max_length=10)),
                ('payer_email', models.EmailField(max_length=254, null=True)),
                ('payer_name', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('payment_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='api.product')),
            ],
        ),
    ]
