# Generated by Django 5.0.1 on 2024-02-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_businesspayment_payment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspayment',
            name='payment_owner',
            field=models.CharField(max_length=100),
        ),
    ]
