# Generated by Django 5.0.1 on 2024-02-12 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_businesspayment_payment_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LipilaDisbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_account', models.CharField(max_length=30)),
                ('payment_amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=55)),
                ('transaction_id', models.CharField(max_length=20)),
                ('payment_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid', to='api.myuser')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
