# Generated by Django 5.0.1 on 2024-02-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_lipiladisbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(choices=[('KITWE', 'Kitwe'), ('LUSAKA', 'Lusaka')], default='KITWE', max_length=9),
        ),
        migrations.AddField(
            model_name='myuser',
            name='company',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='country',
            field=models.CharField(default='Zambia', max_length=10),
        ),
    ]
