# Generated by Django 5.0.1 on 2024-02-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_myuser_address_myuser_city_myuser_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='assets/static/img/profiles/'),
        ),
    ]
