# Generated by Django 5.0.1 on 2024-10-02 12:14

import django.core.files.storage
import django.core.files.storage.filesystem
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patron', '0007_rename_payer_payment_authenticated_payer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('short_reference', models.CharField(blank=True, max_length=255)),
                ('long_reference', models.TextField(blank=True, max_length=500)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(max_length=255)),
                ('is_private', models.BooleanField(default=False)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to=django.core.files.storage.filesystem.FileSystemStorage.path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'mp4', 'avi', 'mov', 'pdf', 'png', 'jpg', 'jpeg'])])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to=settings.AUTH_USER_MODEL)),
                ('tiers', models.ManyToManyField(blank=True, related_name='multimedia', to='patron.tier')),
            ],
        ),
    ]
