# Generated by Django 5.0.1 on 2024-09-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_airteltransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lipilacollection',
            old_name='description',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='lipilacollection',
            old_name='reference_id',
            new_name='transaction_id',
        ),
        migrations.RenameField(
            model_name='lipiladisbursement',
            old_name='description',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='lipiladisbursement',
            old_name='reference_id',
            new_name='transaction_id',
        ),
    ]
