# Generated by Django 5.0.1 on 2024-10-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_lipilacollection_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomoColTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('wallet_type', models.CharField(max_length=55)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('msisdn', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.DeleteModel(
            name='AirtelTransaction',
        ),
        migrations.DeleteModel(
            name='LipilaCollection',
        ),
    ]
