# Generated by Django 5.0.1 on 2024-08-17 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payoutaccount',
            old_name='user',
            new_name='user_id',
        ),
    ]
