# Generated by Django 5.0.1 on 2024-08-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_creatorprofile_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutaccount',
            name='account_currency',
            field=models.CharField(blank=True, default='ZMW', max_length=50, null=True),
        ),
    ]
