# Generated by Django 5.0.1 on 2024-10-03 13:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_usersocialauth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='creator_category',
            field=models.CharField(choices=[('', ''), ('artist', 'Visual Creator'), ('musician', 'Musician-Actor'), ('filmmaker', 'Filmmaker-Content Creator'), ('writer', 'Writer-Poet'), ('educator', 'Educator-Mentor'), ('craftmaker', 'Craft Maker-Designer'), ('other', 'Other')], default='', max_length=50),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
