# Generated by Django 5.0.1 on 2024-10-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_creatorprofile_creator_category_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocialauth',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
