# Generated by Django 5.0.1 on 2024-08-17 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('msisdn', models.CharField(max_length=300, null=True)),
                ('reference_id', models.CharField(max_length=40, unique=True)),
                ('wallet_type', models.CharField(choices=[('', ''), ('mtn', 'mtn'), ('airtel', 'airtel')], default='', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=20)),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions_received', to='accounts.creatorprofile')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('price', models.IntegerField(choices=[(10, 'K10'), (20, 'K20'), (50, 'K50')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible_to_fans', models.BooleanField(default=True)),
                ('is_editable', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='accounts.creatorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TierSubscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='patron.tier')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('msisdn', models.CharField(max_length=300)),
                ('reference_id', models.CharField(max_length=40, unique=True)),
                ('wallet_type', models.CharField(choices=[('', ''), ('mtn', 'mtn'), ('airtel', 'airtel')], default='', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=20)),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='patron.tiersubscriptions')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('msisdn', models.CharField(max_length=300, null=True)),
                ('send_money_to', models.CharField(max_length=300, null=True)),
                ('reference_id', models.CharField(max_length=40, unique=True)),
                ('wallet_type', models.CharField(choices=[('', ''), ('mtn', 'mtn'), ('airtel', 'airtel')], default='', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=20)),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tranfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_number', models.CharField(max_length=30)),
                ('reference_id', models.CharField(max_length=120)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=20)),
                ('wallet_type', models.CharField(choices=[('', ''), ('mtn', 'mtn'), ('airtel', 'airtel')], default='', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='accounts.creatorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedWithdrawals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_date', models.DateTimeField(auto_now_add=True)),
                ('request_date', models.CharField(blank=True, max_length=120, null=True)),
                ('reference_id', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=20)),
                ('wallet_type', models.CharField(choices=[('', ''), ('mtn', 'mtn'), ('airtel', 'airtel')], default='mtn', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('withdrawal_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='patron.withdrawalrequest')),
            ],
        ),
    ]
