# Generated by Django 5.0.1 on 2024-08-21 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_payoutaccount_account_currency'),
        ('patron', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributions',
            name='payer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ContributionsUnauth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.CharField(max_length=15, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('payer_account_number', models.CharField(max_length=300, null=True)),
                ('reference_id', models.CharField(max_length=40, unique=True)),
                ('wallet_type', models.CharField(choices=[('', ''), ('mtn', 'mtn'), ('airtel', 'airtel')], default='', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=20)),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_received', to='accounts.creatorprofile')),
            ],
        ),
    ]
