# Generated by Django 5.0.1 on 2024-09-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0002_alter_contributions_payer_contributionsunauth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributions',
            old_name='description',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='contributions',
            old_name='reference_id',
            new_name='transaction_id',
        ),
        migrations.RenameField(
            model_name='contributionsunauth',
            old_name='description',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='contributionsunauth',
            old_name='reference_id',
            new_name='transaction_id',
        ),
        migrations.RenameField(
            model_name='processedwithdrawals',
            old_name='reference_id',
            new_name='transaction_id',
        ),
        migrations.RenameField(
            model_name='subscriptionpayments',
            old_name='description',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='subscriptionpayments',
            old_name='reference_id',
            new_name='transaction_id',
        ),
        migrations.RenameField(
            model_name='tier',
            old_name='description',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='description',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='reference_id',
            new_name='transaction_id',
        ),
        migrations.RenameField(
            model_name='withdrawalrequest',
            old_name='reference_id',
            new_name='transaction_id',
        ),
    ]
