# Generated by Django 5.0.1 on 2024-10-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0003_rename_description_contributions_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributions',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contributionsunauth',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contributionsunauth',
            name='payer',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
