# Generated by Django 5.0.1 on 2024-10-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0005_rename_contributions_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentanonymous',
            name='payer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
