# coding: utf-8

"""
    Payments V1

    To facilitate the capability for consumers to make a payment or refund to service providers.

    The version of the OpenAPI document: v1.0
    Contact: developer-support@mtn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.promise_to_pay_request import PromiseToPayRequest

class TestPromiseToPayRequest(unittest.TestCase):
    """PromiseToPayRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromiseToPayRequest:
        """Test PromiseToPayRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PromiseToPayRequest`
        """
        model = PromiseToPayRequest()
        if include_optional:
            return PromiseToPayRequest(
                billing_account_no = '903442299RC',
                service_name = 'Outstanding Dues',
                promise_open_date = '2020-08-12T11:04:53.668Z',
                promise_amount = 1290.0,
                number_of_installments = '3',
                duration_uom = 'Month',
                promise_threshold = '100'
            )
        else:
            return PromiseToPayRequest(
        )
        """

    def testPromiseToPayRequest(self):
        """Test PromiseToPayRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
