# coding: utf-8

"""
    Payments V1

    To facilitate the capability for consumers to make a payment or refund to service providers.

    The version of the OpenAPI document: v1.0
    Contact: developer-support@mtn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.promise_to_pay_eligibility_response_data import PromiseToPayEligibilityResponseData

class TestPromiseToPayEligibilityResponseData(unittest.TestCase):
    """PromiseToPayEligibilityResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromiseToPayEligibilityResponseData:
        """Test PromiseToPayEligibilityResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PromiseToPayEligibilityResponseData`
        """
        model = PromiseToPayEligibilityResponseData()
        if include_optional:
            return PromiseToPayEligibilityResponseData(
                promise_to_pay_eligibility_details = openapi_client.models.promise_to_pay_eligibility.promiseToPayEligibility(
                    eligibility_status = 'Eligible', 
                    account_balance = '9274', 
                    minimum_amount = '1000', 
                    payment_start_date = '17-10-2022', )
            )
        else:
            return PromiseToPayEligibilityResponseData(
        )
        """

    def testPromiseToPayEligibilityResponseData(self):
        """Test PromiseToPayEligibilityResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
