# coding: utf-8

"""
    Payments V1

    To facilitate the capability for consumers to make a payment or refund to service providers.

    The version of the OpenAPI document: v1.0
    Contact: developer-support@mtn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.transaction_type_enum import TransactionTypeEnum

class TestTransactionTypeEnum(unittest.TestCase):
    """TransactionTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionTypeEnum(self):
        """Test TransactionTypeEnum"""
        # inst = TransactionTypeEnum()

if __name__ == '__main__':
    unittest.main()
