# coding: utf-8

"""
    Payments V1

    To facilitate the capability for consumers to make a payment or refund to service providers.

    The version of the OpenAPI document: v1.0
    Contact: developer-support@mtn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.bank_card import BankCard

class TestBankCard(unittest.TestCase):
    """BankCard unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BankCard:
        """Test BankCard
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BankCard`
        """
        model = BankCard()
        if include_optional:
            return BankCard(
                brand = 'Visa',
                type = 'Credit',
                card_number = 'xxxx xxxx xxx xxx',
                expiration_date = '2021-07-21T17:32:28Z',
                cvv = '123',
                last_four_digits = '1234',
                name_on_card = 'Bruce Wayne',
                bank = 'Bank of Gotham',
                pin = '123'
            )
        else:
            return BankCard(
        )
        """

    def testBankCard(self):
        """Test BankCard"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
