# coding: utf-8

"""
    Payments V1

    To facilitate the capability for consumers to make a payment or refund to service providers.

    The version of the OpenAPI document: v1.0
    Contact: developer-support@mtn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_method_type_enum import PaymentMethodTypeEnum

class TestPaymentMethodTypeEnum(unittest.TestCase):
    """PaymentMethodTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentMethodTypeEnum(self):
        """Test PaymentMethodTypeEnum"""
        # inst = PaymentMethodTypeEnum()

if __name__ == '__main__':
    unittest.main()
