# coding: utf-8

"""
    Payments V1

    To facilitate the capability for consumers to make a payment or refund to service providers.

    The version of the OpenAPI document: v1.0
    Contact: developer-support@mtn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.promise_detail import PromiseDetail

class TestPromiseDetail(unittest.TestCase):
    """PromiseDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromiseDetail:
        """Test PromiseDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PromiseDetail`
        """
        model = PromiseDetail()
        if include_optional:
            return PromiseDetail(
                installment_due_amount = '266.67',
                installment_end_date = '2020-08-12T11:04:53.668Z',
                query_number = 'FT172145YB21',
                installment_start_date = '2020-08-12T11:04:53.668Z'
            )
        else:
            return PromiseDetail(
        )
        """

    def testPromiseDetail(self):
        """Test PromiseDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
