# coding: utf-8

"""
    Payments V1

    To facilitate the capability for consumers to make a payment or refund to service providers.

    The version of the OpenAPI document: v1.0
    Contact: developer-support@mtn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.digital_wallet import DigitalWallet

class TestDigitalWallet(unittest.TestCase):
    """DigitalWallet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DigitalWallet:
        """Test DigitalWallet
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DigitalWallet`
        """
        model = DigitalWallet()
        if include_optional:
            return DigitalWallet(
                service = 'MoMo',
                wallet_id = '233364654737',
                wallet_uri = 'https://paypal.me/johndoe'
            )
        else:
            return DigitalWallet(
        )
        """

    def testDigitalWallet(self):
        """Test DigitalWallet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
