# coding: utf-8

"""
    Payments V1

    To facilitate the capability for consumers to make a payment or refund to service providers.

    The version of the OpenAPI document: v1.0
    Contact: developer-support@mtn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.payment_history_api import PaymentHistoryApi


class TestPaymentHistoryApi(unittest.TestCase):
    """PaymentHistoryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PaymentHistoryApi()

    def tearDown(self) -> None:
        pass

    def test_get_payment_history(self) -> None:
        """Test case for get_payment_history

        Get a list of payments made on a reference or by a customer id
        """
        pass


if __name__ == '__main__':
    unittest.main()
