# coding: utf-8

"""
    Payments V1

    To facilitate the capability for consumers to make a payment or refund to service providers.

    The version of the OpenAPI document: v1.0
    Contact: developer-support@mtn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class BankAccountDebit(BaseModel):
    """
    Detailed information for a bank account debit.
    """ # noqa: E501
    account_number: Optional[StrictStr] = Field(default=None, description="Bank Account Number (this could refer to the IBAN or SWIFT number).", alias="accountNumber")
    account_number_type: Optional[StrictStr] = Field(default=None, description="Type of account number. e.g. IBAN, SWIFT.", alias="accountNumberType")
    bic: Optional[StrictStr] = Field(default=None, description="Business Identifier Code/Swift code of the financial institution where the account is located.", alias="BIC")
    owner: Optional[StrictStr] = Field(default=None, description="Owner of the bank account.")
    bank: Optional[StrictStr] = Field(default=None, description="Display nam of the bank.")
    __properties: ClassVar[List[str]] = ["accountNumber", "accountNumberType", "BIC", "owner", "bank"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BankAccountDebit from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BankAccountDebit from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accountNumber": obj.get("accountNumber"),
            "accountNumberType": obj.get("accountNumberType"),
            "BIC": obj.get("BIC"),
            "owner": obj.get("owner"),
            "bank": obj.get("bank")
        })
        return _obj


