# coding: utf-8

"""
    Payments V1

    To facilitate the capability for consumers to make a payment or refund to service providers.

    The version of the OpenAPI document: v1.0
    Contact: developer-support@mtn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.money_type import MoneyType
from typing import Optional, Set
from typing_extensions import Self

class LoyaltyBalances(BaseModel):
    """
    Contains all the loyalty balances associated with a customer.
    """ # noqa: E501
    generated_amount: Optional[MoneyType] = Field(default=None, alias="generatedAmount")
    consumed_amount: Optional[MoneyType] = Field(default=None, alias="consumedAmount")
    new_balance: Optional[MoneyType] = Field(default=None, alias="newBalance")
    __properties: ClassVar[List[str]] = ["generatedAmount", "consumedAmount", "newBalance"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LoyaltyBalances from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of generated_amount
        if self.generated_amount:
            _dict['generatedAmount'] = self.generated_amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of consumed_amount
        if self.consumed_amount:
            _dict['consumedAmount'] = self.consumed_amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of new_balance
        if self.new_balance:
            _dict['newBalance'] = self.new_balance.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LoyaltyBalances from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "generatedAmount": MoneyType.from_dict(obj["generatedAmount"]) if obj.get("generatedAmount") is not None else None,
            "consumedAmount": MoneyType.from_dict(obj["consumedAmount"]) if obj.get("consumedAmount") is not None else None,
            "newBalance": MoneyType.from_dict(obj["newBalance"]) if obj.get("newBalance") is not None else None
        })
        return _obj


