# coding: utf-8

"""
    Payments V1

    To facilitate the capability for consumers to make a payment or refund to service providers.

    The version of the OpenAPI document: v1.0
    Contact: developer-support@mtn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.data import Data
from openapi_client.models.payment_response_links import PaymentResponseLinks
from typing import Optional, Set
from typing_extensions import Self

class PaymentResponse(BaseModel):
    """
    PaymentResponse
    """ # noqa: E501
    status_code: Optional[StrictStr] = Field(default=None, description="This is the MADAPI Canonical Error Code (it is 4 characters long and it is not the HTTP Status Code which is 3 characters long). Back-end system errors are mapped to specific canonical error codes which are returned. 0000 is for a success. More information on these mappings can be found on the MADAPI Confluence Page 'Response Codes'", alias="statusCode")
    provider_transaction_id: Optional[StrictStr] = Field(default=None, description="ID of the payment, generated by back-end system. This can be blank if the payment has previously been pre-approved.", alias="providerTransactionId")
    status_message: Optional[StrictStr] = Field(default=None, description="A description of the transaction status.", alias="statusMessage")
    support_message: Optional[StrictStr] = Field(default=None, description="A description used for error handling", alias="supportMessage")
    sequence_no: Optional[StrictStr] = Field(default=None, description="A unique id for tracing all requests", alias="sequenceNo")
    fulfillment_status: Optional[StrictStr] = Field(default=None, description="A description of the transaction fulfillment status.", alias="fulfillmentStatus")
    data: Optional[Data] = None
    links: Optional[PaymentResponseLinks] = Field(default=None, alias="_links")
    __properties: ClassVar[List[str]] = ["statusCode", "providerTransactionId", "statusMessage", "supportMessage", "sequenceNo", "fulfillmentStatus", "data", "_links"]

    @field_validator('fulfillment_status')
    def fulfillment_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Succesful', 'Failed', 'Null']):
            raise ValueError("must be one of enum values ('Succesful', 'Failed', 'Null')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of data
        if self.data:
            _dict['data'] = self.data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict['_links'] = self.links.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "statusCode": obj.get("statusCode"),
            "providerTransactionId": obj.get("providerTransactionId"),
            "statusMessage": obj.get("statusMessage"),
            "supportMessage": obj.get("supportMessage"),
            "sequenceNo": obj.get("sequenceNo"),
            "fulfillmentStatus": obj.get("fulfillmentStatus"),
            "data": Data.from_dict(obj["data"]) if obj.get("data") is not None else None,
            "_links": PaymentResponseLinks.from_dict(obj["_links"]) if obj.get("_links") is not None else None
        })
        return _obj


