# coding: utf-8

"""
    Payments V1

    To facilitate the capability for consumers to make a payment or refund to service providers.

    The version of the OpenAPI document: v1.0
    Contact: developer-support@mtn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class PromiseToPayRequest(BaseModel):
    """
    Payment Request details.
    """ # noqa: E501
    billing_account_no: Optional[StrictStr] = Field(default=None, description="Unique Billing Account number of the customer", alias="billingAccountNo")
    service_name: Optional[StrictStr] = Field(default=None, description="Service name of the payment.", alias="serviceName")
    promise_open_date: Optional[datetime] = Field(default=None, description="Start Date of the Promise.", alias="promiseOpenDate")
    promise_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Amount promised to be paid.", alias="promiseAmount")
    number_of_installments: Optional[StrictStr] = Field(default=None, description="Number of the EMI.", alias="numberOfInstallments")
    duration_uom: Optional[StrictStr] = Field(default=None, description="Unit of Measure for the EMI (can be Month, Week and Year).", alias="durationUOM")
    promise_threshold: Optional[StrictStr] = Field(default=None, description="The Promise Threshold", alias="promiseThreshold")
    __properties: ClassVar[List[str]] = ["billingAccountNo", "serviceName", "promiseOpenDate", "promiseAmount", "numberOfInstallments", "durationUOM", "promiseThreshold"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PromiseToPayRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PromiseToPayRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "billingAccountNo": obj.get("billingAccountNo"),
            "serviceName": obj.get("serviceName"),
            "promiseOpenDate": obj.get("promiseOpenDate"),
            "promiseAmount": obj.get("promiseAmount"),
            "numberOfInstallments": obj.get("numberOfInstallments"),
            "durationUOM": obj.get("durationUOM"),
            "promiseThreshold": obj.get("promiseThreshold")
        })
        return _obj


