# coding: utf-8

"""
    Payments V1

    To facilitate the capability for consumers to make a payment or refund to service providers.

    The version of the OpenAPI document: v1.0
    Contact: developer-support@mtn.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.time_period import TimePeriod
from typing import Optional, Set
from typing_extensions import Self

class RelatedParty(BaseModel):
    """
    Related Entity reference. A related party defines party or party role linked to a specific entity.
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Unique identifier of a related entity.")
    name: Optional[StrictStr] = Field(default=None, description="Name of the related entity.")
    other_name: Optional[StrictStr] = Field(default=None, description="Othername of the related party entity", alias="otherName")
    email: Optional[StrictStr] = Field(default=None, description="Email of the related party entity")
    valid_for: Optional[TimePeriod] = Field(default=None, alias="validFor")
    __properties: ClassVar[List[str]] = ["id", "name", "otherName", "email", "validFor"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RelatedParty from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of valid_for
        if self.valid_for:
            _dict['validFor'] = self.valid_for.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RelatedParty from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "otherName": obj.get("otherName"),
            "email": obj.get("email"),
            "validFor": TimePeriod.from_dict(obj["validFor"]) if obj.get("validFor") is not None else None
        })
        return _obj


